"""
build_demo.py
-------------
Reads your indexed GraphRAG output and writes `demo_data.js`, which `demo.html`
loads to render YOUR real knowledge graph (not the hardcoded sample).

Run this AFTER indexing:
    python build_demo.py

Then open demo.html in a browser.
"""

import json
import sys
from pathlib import Path

import pandas as pd

OUTPUT_DIR = Path("output")
DATA_JS    = Path("demo_data.js")

# Pretty colors per community (cycled).
COMMUNITY_PALETTE = [
    "#E63946", "#2A9D8F", "#E9C46A", "#5E8FC7", "#F4A261",
    "#A8DADC", "#BB8FCE", "#F72585", "#7209B7", "#06A77D",
    "#FF8C42", "#118AB2", "#EF476F", "#FFD166", "#073B4C",
]

# Edge-label trimming so the JSON stays small.
MAX_EDGE_LABEL = 140
MAX_NODE_DESC  = 600


def must_read(name: str) -> pd.DataFrame:
    p = OUTPUT_DIR / name
    if not p.exists():
        sys.exit(
            f"ERROR: {p} not found.\n"
            "Did indexing finish? Run:\n"
            "    python -m graphrag.index --root .\n"
        )
    return pd.read_parquet(p)


def main() -> None:
    print("Reading parquet files from output/ ...")
    entities      = must_read("entities.parquet")
    relationships = must_read("relationships.parquet")
    communities   = must_read("communities.parquet")
    reports_path  = OUTPUT_DIR / "community_reports.parquet"
    reports       = pd.read_parquet(reports_path) if reports_path.exists() else None

    # Build entity-id → title map (relationships use titles, but we want a clean id).
    id_to_title = dict(zip(entities["id"], entities["title"]))

    # Build entity-id → community map. GraphRAG produces a hierarchy; level 0 is
    # the coarsest (broadest) partition — best for "show me the big clusters" demos.
    ent_to_comm: dict[str, int] = {}
    use_level = 0
    base = communities[communities["level"] == use_level] if "level" in communities.columns else communities
    for _, row in base.iterrows():
        cid = int(row["community"])
        for ent_id in row["entity_ids"]:
            ent_to_comm[ent_id] = cid

    # Build community list with titles/summaries from community_reports.
    comm_info: dict[int, dict] = {}
    if reports is not None:
        leaf_reports = reports[reports["level"] == use_level]
        for _, row in leaf_reports.iterrows():
            cid = int(row["community"])
            comm_info[cid] = {
                "id":      cid,
                "title":   str(row.get("title") or f"Community {cid}"),
                "summary": str(row.get("summary") or ""),
                "size":    int(row.get("size") or 0),
            }

    # Make sure every community that has entities also has a record.
    for cid in sorted(set(ent_to_comm.values())):
        comm_info.setdefault(cid, {
            "id": cid,
            "title": f"Community {cid}",
            "summary": "",
            "size": 0,
        })

    # Assign a stable color to each community.
    communities_out = []
    for i, cid in enumerate(sorted(comm_info.keys())):
        rec = comm_info[cid]
        rec["color"] = COMMUNITY_PALETTE[i % len(COMMUNITY_PALETTE)]
        communities_out.append(rec)

    # Build nodes.
    nodes_out = []
    for _, row in entities.iterrows():
        title = str(row["title"])
        ent_type = str(row.get("type") or "unknown").lower()
        desc = str(row.get("description") or "")
        if len(desc) > MAX_NODE_DESC:
            desc = desc[:MAX_NODE_DESC].rstrip() + "…"
        nodes_out.append({
            "id":  title,
            "t":   ent_type,
            "c":   ent_to_comm.get(row["id"], -1),
            "d":   desc,
            "deg": int(row.get("degree") or 0),
        })

    # Build links. Relationships reference entities by title.
    valid_titles = {n["id"] for n in nodes_out}
    links_out = []
    for _, row in relationships.iterrows():
        s = str(row.get("source") or "")
        t = str(row.get("target") or "")
        if s not in valid_titles or t not in valid_titles or s == t:
            continue
        label = str(row.get("description") or "")
        if len(label) > MAX_EDGE_LABEL:
            label = label[:MAX_EDGE_LABEL].rstrip() + "…"
        try:
            weight = float(row.get("weight") or 1.0)
        except (TypeError, ValueError):
            weight = 1.0
        links_out.append({"s": s, "t": t, "l": label, "w": weight})

    data = {
        "nodes":       nodes_out,
        "links":       links_out,
        "communities": communities_out,
        "stats": {
            "entities":      len(nodes_out),
            "relationships": len(links_out),
            "communities":   len(communities_out),
        },
    }

    payload = json.dumps(data, ensure_ascii=False, indent=2)
    DATA_JS.write_text(
        "// AUTO-GENERATED by build_demo.py — do not edit.\n"
        "// Regenerate with: python build_demo.py\n"
        f"window.GRAPH_DATA = {payload};\n",
        encoding="utf-8",
    )

    print(f"Wrote {DATA_JS}")
    print(f"  {len(nodes_out)} entities")
    print(f"  {len(links_out)} relationships")
    print(f"  {len(communities_out)} communities")
    print("\nNow open demo.html in your browser.")


if __name__ == "__main__":
    main()
