// AUTO-GENERATED by build_demo.py — do not edit.
// Regenerate with: python build_demo.py
window.GRAPH_DATA = {
  "nodes": [
    {
      "id": "OPNEAI",
      "t": "organization",
      "c": -1,
      "d": "OpenAI is a company founded in 2015 by Sam Altman, Elon Musk, Greg Brockman, and others, known for developing the GPT series of large language models, including GPT-4 released in March 2023.",
      "deg": 0
    },
    {
      "id": "SAM ALTMAN",
      "t": "person",
      "c": -1,
      "d": "Sam Altman is one of the founders of OpenAI and a significant figure in the AI ecosystem.",
      "deg": 0
    },
    {
      "id": "ELON MUSK",
      "t": "person",
      "c": -1,
      "d": "Elon Musk is one of the founders of OpenAI and a well-known entrepreneur in the technology sector.",
      "deg": 0
    },
    {
      "id": "GREG BROCKMAN",
      "t": "person",
      "c": -1,
      "d": "Greg Brockman is one of the founders of OpenAI and has played a key role in its development efforts.",
      "deg": 0
    },
    {
      "id": "MICROSOFT",
      "t": "organization",
      "c": -1,
      "d": "Microsoft is a major strategic partner of OpenAI, incorporating its models into various Microsoft products and investing billions of dollars.",
      "deg": 1
    },
    {
      "id": "AZURE OPENAI SERVICE",
      "t": "organization",
      "c": -1,
      "d": "Azure OpenAI Service is a platform by Microsoft that integrates OpenAI models.",
      "deg": 0
    },
    {
      "id": "GITHUB COPILOT",
      "t": "organization",
      "c": -1,
      "d": "GitHub Copilot is a product by Microsoft that uses OpenAI models for coding assistance.",
      "deg": 0
    },
    {
      "id": "MICROSOFT 365 COPILOT",
      "t": "organization",
      "c": -1,
      "d": "Microsoft 365 Copilot is a Microsoft product that integrates OpenAI models to assist with office tasks.",
      "deg": 0
    },
    {
      "id": "ANTHROPIC",
      "t": "organization",
      "c": -1,
      "d": "Anthropic is a company founded in 2021 by Dario Amodei, Daniela Amodei, and former OpenAI researchers, focusing on AI safety and developing the Claude family of models.",
      "deg": 4
    },
    {
      "id": "DARIO AMODEI",
      "t": "person",
      "c": -1,
      "d": "Dario Amodei is a founder of Anthropic and a leader in AI research focused on safety.",
      "deg": 1
    },
    {
      "id": "DANIELA AMODEI",
      "t": "person",
      "c": -1,
      "d": "Daniela Amodei is a founder of Anthropic and contributes to its AI safety research.",
      "deg": 1
    },
    {
      "id": "GOOGLE",
      "t": "organization",
      "c": -1,
      "d": "Google is a significant investor in Anthropic and developed the Gemini family of models through its Google DeepMind division.",
      "deg": 7
    },
    {
      "id": "AMAZON",
      "t": "organization",
      "c": -1,
      "d": "Amazon is an investor in Anthropic, making multi-billion dollar commitments towards AI research and development.",
      "deg": 2
    },
    {
      "id": "GOOGLE DEEPMIND",
      "t": "organization",
      "c": -1,
      "d": "Google DeepMind is a merged entity from Google Brain and DeepMind, known for the Gemini family of models and AlphaFold.",
      "deg": 4
    },
    {
      "id": "META AI",
      "t": "organization",
      "c": -1,
      "d": "Meta AI is responsible for the Llama series of open-weight models and adopts an open approach to AI model development.",
      "deg": 4
    },
    {
      "id": "MISTRAL AI",
      "t": "organization",
      "c": -1,
      "d": "Mistral AI is a French startup developed by former DeepMind and Meta researchers focused on creating efficient open models.",
      "deg": 2
    },
    {
      "id": "NVIDIA",
      "t": "organization",
      "c": -1,
      "d": "NVIDIA is the leading supplier of GPUs crucial for AI training and inference, partnering with major players like Microsoft, Google, and Amazon.",
      "deg": 5
    },
    {
      "id": "LANGCHAIN",
      "t": "organization",
      "c": -1,
      "d": "LangChain is an open-source framework aiding developers in building applications using large language models.",
      "deg": 0
    },
    {
      "id": "MICROSOFT GRAPHRAG",
      "t": "organization",
      "c": -1,
      "d": "Microsoft GraphRAG is developed by Microsoft Research and enhances retrieval-augmented generation using knowledge graphs.",
      "deg": 1
    },
    {
      "id": "GOOGLE BRAIN",
      "t": "organization",
      "c": -1,
      "d": "Google Brain was a division of Google that merged with DeepMind to form Google DeepMind in 2023.",
      "deg": 1
    },
    {
      "id": "DEEP MIND",
      "t": "organization",
      "c": -1,
      "d": "Deep Mind was a research entity working on AI projects like AlphaFold and merged with Google Brain to form Google DeepMind.",
      "deg": 1
    },
    {
      "id": "EVENT",
      "t": "event",
      "c": -1,
      "d": "The merger of Google Brain and DeepMind in 2023 resulted in the creation of Google DeepMind, a significant event in AI development.",
      "deg": 0
    },
    {
      "id": "CONSTITUTIONAL AI",
      "t": "event",
      "c": -1,
      "d": "Constitutional AI is a training methodology developed by Anthropic to enhance AI safety and compliance.",
      "deg": 0
    },
    {
      "id": "GEMINI ULTRA",
      "t": "event",
      "c": -1,
      "d": "Gemini Ultra is part of Google DeepMind's Gemini model family, representing a high-capability tier model.",
      "deg": 1
    },
    {
      "id": "GEMINI PRO",
      "t": "event",
      "c": -1,
      "d": "Gemini Pro is a tier in the Gemini model family developed by Google DeepMind, offering balanced AI capabilities.",
      "deg": 1
    },
    {
      "id": "GEMINI NANO",
      "t": "event",
      "c": -1,
      "d": "Gemini Nano is a model tier by Google DeepMind, optimized for efficiency and low resource usage.",
      "deg": 1
    },
    {
      "id": "ALPHAFOLD",
      "t": "event",
      "c": -1,
      "d": "AlphaFold is a significant AI model developed by DeepMind that solved the protein folding problem.",
      "deg": 0
    },
    {
      "id": "LLAMA 2",
      "t": "event",
      "c": -1,
      "d": "Llama 2 is part of Meta AI’s series of open-weight models, widely used for custom AI application development.",
      "deg": 1
    },
    {
      "id": "LLAMA 3",
      "t": "event",
      "c": -1,
      "d": "Llama 3 is a continuation of Meta AI's open-weight model series, advancing research and commercial AI application use.",
      "deg": 1
    },
    {
      "id": "MISTRAL 7B",
      "t": "event",
      "c": -1,
      "d": "Mistral 7B is an efficient open model developed by Mistral AI focusing on high performance with fewer parameters.",
      "deg": 1
    },
    {
      "id": "MIXTRAL 8X7B",
      "t": "event",
      "c": -1,
      "d": "Mixtral 8x7B is an advanced model by Mistral AI, known for its innovative techniques in efficiency and performance.",
      "deg": 1
    },
    {
      "id": "H100 GPUS",
      "t": "event",
      "c": -1,
      "d": "H100 GPUs are part of NVIDIA's range of GPUs critical to AI training and inference across major technology companies.",
      "deg": 1
    },
    {
      "id": "A100 GPUS",
      "t": "event",
      "c": -1,
      "d": "A100 GPUs are a product of NVIDIA designed to support intensive AI tasks in various data centers worldwide.",
      "deg": 1
    },
    {
      "id": "CUDA",
      "t": "event",
      "c": -1,
      "d": "CUDA is NVIDIA's parallel computing platform and application programming interface model crucial for AI operations.",
      "deg": 1
    },
    {
      "id": "TRANSFORMER ARCHITECTURE",
      "t": "event",
      "c": -1,
      "d": "The Transformer architecture, introduced by Google, underlies most modern large language models using attention mechanisms for efficient training on large data sets.",
      "deg": 1
    },
    {
      "id": "RETRIEVAL-AUGMENTED GENERATION (RAG)",
      "t": "event",
      "c": -1,
      "d": "RAG is a system combining retrieval with generative models introduced by Facebook AI Research to enhance large language model capabilities with external knowledge.",
      "deg": 1
    },
    {
      "id": "NOVA AI",
      "t": "organization",
      "c": 5,
      "d": "Nova AI is an innovative company specializing in artificial intelligence document processing, known for its significant growth trajectory and technological advancements. Founded in 2018 by three Stanford PhD students, Nova AI has established itself as a key player in the AI technology sector. The company's initial product, Lumina, is an enterprise-level platform designed for document understanding, catering to businesses seeking efficient and intelligent document processing solutions. Building on the success of Lumina, Nova AI further developed GraphMind, a sophisticated system architecture ai…",
      "deg": 16
    },
    {
      "id": "PRIYA KAPOOR",
      "t": "person",
      "c": 5,
      "d": "Priya Kapoor is the Chief Executive Officer and co-founder of Nova AI, a leading technology company known for its innovations in artificial intelligence. Alongside her co-founders, Marcus Chen and Sofia Reyes, Priya has carved a significant niche in the tech industry, particularly in the field of natural language processing. Her leadership and vision have been pivotal in driving the company's growth and strategic direction. Nova AI, under Priya's stewardship, has announced ambitious plans for a public offering, signaling confidence in its continued success and market expansion.\n\nPriya's accomp…",
      "deg": 2
    },
    {
      "id": "MARCUS CHEN",
      "t": "person",
      "c": 5,
      "d": "Marcus Chen is a prominent figure in the field of artificial intelligence, most notably recognized as a co-founder and the Chief Technology Officer (CTO) of Nova AI. His significant contributions to the company, particularly in the realm of computer vision, have not only advanced technological innovation but have also made him a billionaire, thanks to his equity stake in Nova AI. In addition to his entrepreneurial success, Chen expanded his influence in the academic and technological community by joining the board of the Alan Turing Institute, underscoring his dedication to advancing AI resear…",
      "deg": 2
    },
    {
      "id": "SOFIA REYES",
      "t": "person",
      "c": 6,
      "d": "Sofia Reyes is a pivotal leader at Nova AI, where she serves as the Vice President of Engineering. She has made significant contributions to the company, particularly in the customization of GraphMind for Japanese-language documents, a project she spearheaded alongside Yuki Tanaka. Her expertise lies in distributed systems and databases, which has been instrumental in achieving the strategic goals of Nova AI. Through her technical acumen and leadership, Sofia Reyes has played a substantial role in driving the company's success and fostering technological innovations that enhance its operations…",
      "deg": 3
    },
    {
      "id": "HORIZON VENTURES",
      "t": "organization",
      "c": 5,
      "d": "Horizon Ventures is a venture capital firm that led the Series A and B funding rounds for Nova AI, supporting its growth and development.",
      "deg": 2
    },
    {
      "id": "JANET YEE",
      "t": "person",
      "c": 5,
      "d": "Janet Yee is a partner at Horizon Ventures who played a significant role in funding Nova AI. She shifted her focus from DocuMind to Nova AI over time.",
      "deg": 2
    },
    {
      "id": "DOCUMIND",
      "t": "organization",
      "c": 2,
      "d": "DocuMind is an AI-driven document management company that has demonstrated resilience and innovation in the technology sector. Founded by former Google engineer Trevor Blake, DocuMind has navigated challenging times, including recovery from a past scandal that threatened its reputation. This recovery speaks volumes about the company's capability to manage crises and regain its position in the market.\n\nDocuMind has established itself as a formidable competitor in the AI document management industry. The company has successfully secured substantial funding, which has been instrumental in the dev…",
      "deg": 4
    },
    {
      "id": "TREVOR BLAKE",
      "t": "person",
      "c": 2,
      "d": "Trevor Blake is the founder of DocuMind and a former Google engineer. He led the company through various challenges and product launches.",
      "deg": 1
    },
    {
      "id": "STELLAR SYSTEMS",
      "t": "organization",
      "c": 4,
      "d": "Stellar Systems is an AI company specializing in healthcare document processing. Initially gaining recognition for its innovative approach, the company developed MedReader, a flagship product designed for medical document understanding. MedReader utilizes advanced artificial intelligence to enhance the interpretation and management of complex healthcare documentation, positioning Stellar Systems as a leader in the sector.\n\nFacing competition from Nova AI and other industry players, Stellar Systems strategically pivoted to maintain its competitive edge. In response to the competitive landscape,…",
      "deg": 6
    },
    {
      "id": "LEILA NOURI",
      "t": "person",
      "c": 4,
      "d": "Leila Nouri is a prominent figure in the technology and healthcare sectors. She is the founder of Stellar Systems, a company renowned for its innovative solutions in healthcare document processing. Under her leadership, Stellar Systems developed cutting-edge technologies that streamlined and improved the efficiency of handling healthcare documents. A significant achievement in her career was the development and showcasing of MedReader, a revolutionary product that gained significant attention at various AI conferences for its advanced capabilities. \n\nAs the former CEO of Stellar Systems, Leila…",
      "deg": 1
    },
    {
      "id": "CLOUD BASE",
      "t": "organization",
      "c": 1,
      "d": "CloudBase is the third-largest cloud computing provider in North America. It entered a strategic partnership with Nova AI to host GraphMind on its platform.",
      "deg": 2
    },
    {
      "id": "HANNAH PARK",
      "t": "person",
      "c": 1,
      "d": "Hannah Park is the CTO of CloudBase who announced the strategic partnership with Nova AI as a transformational moment for enterprise AI.\"",
      "deg": 1
    },
    {
      "id": "DAVID WU",
      "t": "person",
      "c": 2,
      "d": "David Wu is a security researcher from the University of California, Berkeley, who uncovered a data leakage vulnerability in DocuMind's Cognify product.",
      "deg": 1
    },
    {
      "id": "ALAN HOFFMAN",
      "t": "person",
      "c": 5,
      "d": "Professor Alan Hoffman is a Stanford professor who advised Priya Kapoor and contributed academic validation for Nova AI's GraphMind architecture.",
      "deg": 1
    },
    {
      "id": "TECHGIANT CORP",
      "t": "organization",
      "c": 3,
      "d": "TechGiant Corp, a major cloud computing company headquartered in Redmond, Washington, actively participated in Nova AI's Series B funding round. This strategic move underscores TechGiant Corp's interest in artificial intelligence technologies and its strategy to expand its footprint in AI-driven solutions. Following their investment in Nova AI, TechGiant Corp took a noteworthy step by introducing a competing product, DocuAI. This product marks an expansion of TechGiant Corp's offerings, emphasizing its commitment to innovation and competitive posture in the AI landscape. The launch of DocuAI h…",
      "deg": 3
    },
    {
      "id": "APEX CAPITAL",
      "t": "organization",
      "c": 0,
      "d": "Apex Capital, led by CEO Robert Kim, participated in Nova AI's Series B funding round alongside Horizon Ventures and TechGiant Corp.",
      "deg": 2
    },
    {
      "id": "ROBERT KIM",
      "t": "person",
      "c": 0,
      "d": "Robert Kim is the CEO of Apex Capital, which invested in Nova AI during its Series B funding round.",
      "deg": 1
    },
    {
      "id": "EMMA FITZGERALD",
      "t": "person",
      "c": 5,
      "d": "Emma Fitzgerald is the Regional Director leading Nova AI's first international office in London focusing on the European market.",
      "deg": 1
    },
    {
      "id": "TECHSTAR JAPAN",
      "t": "organization",
      "c": 5,
      "d": "TechStar Japan is a prominent technology conglomerate based in Japan, known for its significant influence and leadership in the tech industry. The company has established a strategic partnership with Nova AI, reflecting its commitment to enhancing technological capabilities and expanding its market reach. Through this collaboration, TechStar Japan has gained access to Nova AI's extensive customer base, which includes 3,000 enterprise clients across various sectors. This partnership underscores TechStar Japan's dedication to innovation and its strategic efforts to integrate advanced artificial…",
      "deg": 2
    },
    {
      "id": "YUKI TANAKA",
      "t": "person",
      "c": 6,
      "d": "Yuki Tanaka serves as the director of partnerships at TechStar Japan, where they play a pivotal role in fostering strategic collaborations. Yuki is particularly noted for their work with Nova AI, focusing on Japanese-language documents, which underscores their expertise in language-specific technological applications. Additionally, Yuki collaborates with Sofia Reyes to tailor GraphMind for Japanese clients, demonstrating their commitment to adapting cutting-edge technology platforms to meet the unique needs of their local market. Through these initiatives, Yuki Tanaka exemplifies a dedication…",
      "deg": 2
    },
    {
      "id": "PALO ALTO",
      "t": "geo",
      "c": 5,
      "d": "Palo Alto is a city in Silicon Valley, California, known for being a central hub for tech startups, including Nova AI's founding location.",
      "deg": 1
    },
    {
      "id": "SAN FRANCISCO",
      "t": "geo",
      "c": 2,
      "d": "San Francisco is a major city in California and the location of Nova AI's rival DocuMind's operations.",
      "deg": 1
    },
    {
      "id": "SEATTLE",
      "t": "geo",
      "c": 4,
      "d": "Seattle is a city in Washington state, home to Nova AI's competitor, Stellar Systems.",
      "deg": 1
    },
    {
      "id": "REDMOND",
      "t": "geo",
      "c": 3,
      "d": "Redmond is a city in Washington state, home to TechGiant Corp, a major cloud computing company involved in Nova AI's funding.",
      "deg": 1
    },
    {
      "id": "GOLDMAN SACHS",
      "t": "organization",
      "c": 5,
      "d": "Goldman Sachs was one of the underwriters for Nova AI's IPO",
      "deg": 1
    },
    {
      "id": "MORGAN STANLEY",
      "t": "organization",
      "c": 5,
      "d": "Morgan Stanley was one of the underwriters for Nova AI's IPO",
      "deg": 1
    },
    {
      "id": "DANIEL ORTEGA",
      "t": "person",
      "c": 5,
      "d": "Daniel Ortega is the CFO of Nova AI who accompanied Priya Kapoor on the IPO roadshow",
      "deg": 1
    },
    {
      "id": "NASDAQ",
      "t": "organization",
      "c": -1,
      "d": "NASDAQ is the stock exchange where Nova AI went public",
      "deg": 3
    },
    {
      "id": "JAMES OKONKWO",
      "t": "person",
      "c": 4,
      "d": "James Okonkwo is the new CEO of Stellar Systems leading their pivot into knowledge graphs",
      "deg": 1
    },
    {
      "id": "DR. AMY LIU",
      "t": "person",
      "c": 4,
      "d": "Dr. Amy Liu was hired by Stellar Systems from Nova AI to head their Stellar Graph development team",
      "deg": 1
    },
    {
      "id": "ALAN TURING INSTITUTE",
      "t": "organization",
      "c": 5,
      "d": "Alan Turing Institute is a research institution where Marcus Chen joined the board",
      "deg": 1
    },
    {
      "id": "Y COMBINATOR",
      "t": "organization",
      "c": 6,
      "d": "Y Combinator is an accelerator program where Sofia Reyes became a mentor",
      "deg": 1
    },
    {
      "id": "DOCUAI",
      "t": "organization",
      "c": 3,
      "d": "DocuAI is a competing product launched by TechGiant Corp integrated with its cloud platform",
      "deg": 1
    },
    {
      "id": "STELLAR GRAPH",
      "t": "organization",
      "c": 4,
      "d": "Stellar Graph is Stellar Systems’ knowledge graph product for the healthcare sector",
      "deg": 1
    },
    {
      "id": "COGNIFY 3.0",
      "t": "organization",
      "c": -1,
      "d": "Cognify 3.0 is DocuMind's improved product version incorporating graph features post overhaul",
      "deg": 0
    },
    {
      "id": "TIMES SQUARE",
      "t": "geo",
      "c": -1,
      "d": "Times Square in New York, where Priya Kapoor rang the opening bell for Nova AI's IPO",
      "deg": 1
    },
    {
      "id": "BOSTON",
      "t": "geo",
      "c": -1,
      "d": "Boston is one of the cities visited during Nova AI's IPO roadshow",
      "deg": 1
    },
    {
      "id": "NEW YORK",
      "t": "geo",
      "c": -1,
      "d": "New York is one of the cities visited during Nova AI's IPO roadshow",
      "deg": 1
    },
    {
      "id": "CHICAGO",
      "t": "geo",
      "c": -1,
      "d": "Chicago is one of the cities visited during Nova AI's IPO roadshow",
      "deg": 0
    },
    {
      "id": "LONDON",
      "t": "geo",
      "c": -1,
      "d": "London is one of the cities visited during Nova AI's IPO roadshow",
      "deg": 0
    }
  ],
  "links": [
    {
      "s": "DARIO AMODEI",
      "t": "ANTHROPIC",
      "l": "Dario Amodei founded Anthropic to focus on AI safety and advanced model development.",
      "w": 9.0
    },
    {
      "s": "DANIELA AMODEI",
      "t": "ANTHROPIC",
      "l": "Daniela Amodei is one of the co-founders of Anthropic, focusing on AI advancements and safety.",
      "w": 9.0
    },
    {
      "s": "GOOGLE",
      "t": "ANTHROPIC",
      "l": "Google has invested significantly in Anthropic, reflecting a strong corporate relationship.",
      "w": 7.0
    },
    {
      "s": "AMAZON",
      "t": "ANTHROPIC",
      "l": "Amazon's major investments in Anthropic indicate a supportive partnership towards advancing AI technologies.",
      "w": 7.0
    },
    {
      "s": "GOOGLE",
      "t": "GOOGLE DEEPMIND",
      "l": "Google is the parent organization of Google DeepMind, developing AI technologies like Gemini.",
      "w": 9.0
    },
    {
      "s": "GOOGLE BRAIN",
      "t": "GOOGLE DEEPMIND",
      "l": "The merger of Google Brain with DeepMind created Google DeepMind, integrating their AI research strengths.",
      "w": 9.0
    },
    {
      "s": "DEEP MIND",
      "t": "GOOGLE DEEPMIND",
      "l": "DeepMind merged with Google Brain to form Google DeepMind, continuing its research efforts in AI.",
      "w": 9.0
    },
    {
      "s": "META AI",
      "t": "GOOGLE DEEPMIND",
      "l": "Meta AI and Google DeepMind represent top-tier entities in AI research, with Meta taking on an open model approach contrasting Google’s stra…",
      "w": 4.0
    },
    {
      "s": "NVIDIA",
      "t": "GOOGLE",
      "l": "NVIDIA collaborates with Google to advance AI processing capabilities using its GPU technologies.",
      "w": 7.0
    },
    {
      "s": "NVIDIA",
      "t": "AMAZON",
      "l": "NVIDIA partners with Amazon, reinforcing its logistical provision of AI models with efficient GPU solutions.",
      "w": 7.0
    },
    {
      "s": "MICROSOFT",
      "t": "MICROSOFT GRAPHRAG",
      "l": "Microsoft GraphRAG was developed under the research umbrella of Microsoft, reflecting an internal expansion of AI capabilities.",
      "w": 8.0
    },
    {
      "s": "GOOGLE",
      "t": "GEMINI ULTRA",
      "l": "Google DeepMind developed Gemini Ultra as a high-capability model within its Gemini family, showcasing peak AI performance.",
      "w": 8.0
    },
    {
      "s": "GOOGLE",
      "t": "GEMINI PRO",
      "l": "Gemini Pro, part of Google DeepMind’s model suite, offers balanced AI capabilities under Google's AI strategies.",
      "w": 8.0
    },
    {
      "s": "GOOGLE",
      "t": "GEMINI NANO",
      "l": "Google DeepMind created Gemini Nano to optimize efficiency and low resource usage in AI model operations.",
      "w": 8.0
    },
    {
      "s": "META AI",
      "t": "LLAMA 2",
      "l": "Llama 2 is part of Meta AI’s open model strategy, promoting research and commercial application access.",
      "w": 8.0
    },
    {
      "s": "META AI",
      "t": "LLAMA 3",
      "l": "Llama 3 continues Meta AI's approach of open access models for widespread use in AI development.",
      "w": 8.0
    },
    {
      "s": "MISTRAL AI",
      "t": "MISTRAL 7B",
      "l": "Mistral AI developed Mistral 7B, demonstrating efficient AI models with fewer parameters for broader accessibility.",
      "w": 8.0
    },
    {
      "s": "MISTRAL AI",
      "t": "MIXTRAL 8X7B",
      "l": "Mixtral 8x7B, created by Mistral AI, utilizes innovative techniques in efficiency and performance optimization.",
      "w": 8.0
    },
    {
      "s": "NVIDIA",
      "t": "H100 GPUS",
      "l": "NVIDIA's H100 GPUs are essential for AI processing, used in AI models and data centers worldwide.",
      "w": 8.0
    },
    {
      "s": "NVIDIA",
      "t": "A100 GPUS",
      "l": "NVIDIA's A100 GPUs are central to supporting intensive AI tasks across different technological infrastructures.",
      "w": 8.0
    },
    {
      "s": "NVIDIA",
      "t": "CUDA",
      "l": "CUDA, developed by NVIDIA, is crucial for enabling parallel computing processes in AI applications.",
      "w": 8.0
    },
    {
      "s": "GOOGLE",
      "t": "TRANSFORMER ARCHITECTURE",
      "l": "Google introduced the Transformer architecture, foundational to modern AI and large language models.",
      "w": 9.0
    },
    {
      "s": "META AI",
      "t": "RETRIEVAL-AUGMENTED GENERATION (RAG)",
      "l": "Meta AI leverages RAG, a Facebook AI Research innovation, for its open model applications and research.",
      "w": 1.0
    },
    {
      "s": "PRIYA KAPOOR",
      "t": "NOVA AI",
      "l": "Priya Kapoor is a co-founder and the CEO of Nova AI. She has recently announced plans for Nova AI to go public. As a pivotal leader in the c…",
      "w": 18.0
    },
    {
      "s": "MARCUS CHEN",
      "t": "NOVA AI",
      "l": "Marcus Chen is a co-founder and the Chief Technology Officer (CTO) of Nova AI, a prominent artificial intelligence company. He played a pivo…",
      "w": 17.0
    },
    {
      "s": "SOFIA REYES",
      "t": "NOVA AI",
      "l": "Sofia Reyes is a co-founder and the VP of Engineering at Nova AI",
      "w": 9.0
    },
    {
      "s": "HORIZON VENTURES",
      "t": "NOVA AI",
      "l": "Horizon Ventures led the Series A and B funding rounds for Nova AI, significantly contributing to its growth",
      "w": 8.0
    },
    {
      "s": "JANET YEE",
      "t": "HORIZON VENTURES",
      "l": "Janet Yee is a partner at Horizon Ventures and played a key role in investing in Nova AI",
      "w": 8.0
    },
    {
      "s": "JANET YEE",
      "t": "NOVA AI",
      "l": "Janet Yee from Horizon Ventures championed the funding rounds for Nova AI",
      "w": 8.0
    },
    {
      "s": "DOCUMIND",
      "t": "NOVA AI",
      "l": "DocuMind is a competing company in the AI document space with Nova AI",
      "w": 5.0
    },
    {
      "s": "TREVOR BLAKE",
      "t": "DOCUMIND",
      "l": "Trevor Blake is the founder of DocuMind",
      "w": 9.0
    },
    {
      "s": "LEILA NOURI",
      "t": "STELLAR SYSTEMS",
      "l": "Leila Nouri is the founder of Stellar Systems",
      "w": 9.0
    },
    {
      "s": "CLOUD BASE",
      "t": "NOVA AI",
      "l": "CloudBase partnered with Nova AI to offer GraphMind on its platform",
      "w": 8.0
    },
    {
      "s": "HANNAH PARK",
      "t": "CLOUD BASE",
      "l": "Hannah Park is the CTO of CloudBase and supported the partnership with Nova AI",
      "w": 8.0
    },
    {
      "s": "DAVID WU",
      "t": "DOCUMIND",
      "l": "David Wu exposed a security vulnerability in DocuMind's product",
      "w": 7.0
    },
    {
      "s": "ALAN HOFFMAN",
      "t": "NOVA AI",
      "l": "Alan Hoffman published academic validation for Nova AI's GraphMind",
      "w": 7.0
    },
    {
      "s": "TECHGIANT CORP",
      "t": "NOVA AI",
      "l": "TechGiant Corp recently participated as an investor in Nova AI's Series B funding round. This investment highlights TechGiant Corp's interes…",
      "w": 13.0
    },
    {
      "s": "APEX CAPITAL",
      "t": "NOVA AI",
      "l": "Apex Capital invested in Nova AI as part of its Series B funding",
      "w": 7.0
    },
    {
      "s": "ROBERT KIM",
      "t": "APEX CAPITAL",
      "l": "Robert Kim is the CEO of Apex Capital, which invested in Nova AI",
      "w": 8.0
    },
    {
      "s": "EMMA FITZGERALD",
      "t": "NOVA AI",
      "l": "Emma Fitzgerald led Nova AI's international expansion into London",
      "w": 8.0
    },
    {
      "s": "TECHSTAR JAPAN",
      "t": "NOVA AI",
      "l": "TechStar Japan partnered with Nova AI to expand its reach in Japan",
      "w": 7.0
    },
    {
      "s": "YUKI TANAKA",
      "t": "TECHSTAR JAPAN",
      "l": "Yuki Tanaka works at TechStar Japan and collaborates with Nova AI for partnerships",
      "w": 1.0
    },
    {
      "s": "NOVA AI",
      "t": "PALO ALTO",
      "l": "Nova AI was founded in a garage in Palo Alto by three Stanford PhD students",
      "w": 7.0
    },
    {
      "s": "DOCUMIND",
      "t": "SAN FRANCISCO",
      "l": "DocuMind operates out of San Francisco, making it geographically close to Nova AI",
      "w": 5.0
    },
    {
      "s": "STELLAR SYSTEMS",
      "t": "SEATTLE",
      "l": "Stellar Systems is based in Seattle",
      "w": 7.0
    },
    {
      "s": "TECHGIANT CORP",
      "t": "REDMOND",
      "l": "TechGiant Corp, a major cloud computing company involved in Nova AI's funding, is based in Redmond",
      "w": 7.0
    },
    {
      "s": "NOVA AI",
      "t": "TECHSTAR JAPAN",
      "l": "Nova AI formed a partnership with TechStar Japan to access its customer base",
      "w": 7.0
    },
    {
      "s": "YUKI TANAKA",
      "t": "SOFIA REYES",
      "l": "Yuki Tanaka collaborated with Sofia Reyes on Japanese-language document customization",
      "w": 6.0
    },
    {
      "s": "GOLDMAN SACHS",
      "t": "NOVA AI",
      "l": "Goldman Sachs acted as an underwriter for Nova AI's IPO",
      "w": 8.0
    },
    {
      "s": "MORGAN STANLEY",
      "t": "NOVA AI",
      "l": "Morgan Stanley acted as an underwriter for Nova AI's IPO",
      "w": 8.0
    },
    {
      "s": "PRIYA KAPOOR",
      "t": "DANIEL ORTEGA",
      "l": "Priya Kapoor and Daniel Ortega led the roadshow for Nova AI's IPO",
      "w": 8.0
    },
    {
      "s": "STELLAR SYSTEMS",
      "t": "NOVA AI",
      "l": "Stellar Systems launched a competing product to Nova AI's offering",
      "w": 5.0
    },
    {
      "s": "JAMES OKONKWO",
      "t": "STELLAR SYSTEMS",
      "l": "James Okonkwo is the CEO leading a new initiative at Stellar Systems",
      "w": 7.0
    },
    {
      "s": "DR. AMY LIU",
      "t": "STELLAR SYSTEMS",
      "l": "Dr. Amy Liu was hired to head the Stellar Graph development at Stellar Systems",
      "w": 7.0
    },
    {
      "s": "MARCUS CHEN",
      "t": "ALAN TURING INSTITUTE",
      "l": "Marcus Chen joined the board of the Alan Turing Institute",
      "w": 6.0
    },
    {
      "s": "SOFIA REYES",
      "t": "Y COMBINATOR",
      "l": "Sofia Reyes became a mentor at Y Combinator",
      "w": 1.0
    },
    {
      "s": "TIMES SQUARE",
      "t": "NASDAQ",
      "l": "NASDAQ is located in Times Square, where Nova AI was publicly listed",
      "w": 7.0
    },
    {
      "s": "NOVA AI",
      "t": "STELLAR SYSTEMS",
      "l": "Stellar Systems launched a competing product directly modeled after Nova AI's GraphMind",
      "w": 5.0
    },
    {
      "s": "NOVA AI",
      "t": "TECHGIANT CORP",
      "l": "TechGiant Corp invested in Nova AI's Series B, indicating a financial relationship despite competing products",
      "w": 4.0
    },
    {
      "s": "STELLAR GRAPH",
      "t": "STELLAR SYSTEMS",
      "l": "Stellar Systems leverages Stellar Graph as its main product in direct competition with Nova AI",
      "w": 7.0
    },
    {
      "s": "BOSTON",
      "t": "NASDAQ",
      "l": "Boston's role in the IPO process of NASDAQ-listed companies was highlighted during Nova AI's roadshow",
      "w": 5.0
    },
    {
      "s": "NEW YORK",
      "t": "NASDAQ",
      "l": "New York and Nasdaq were crucial locations for Nova AI's public market debut",
      "w": 8.0
    },
    {
      "s": "DOCUAI",
      "t": "TECHGIANT CORP",
      "l": "TechGiant Corp developed DocuAI as a direct competitor to Nova AI",
      "w": 1.0
    }
  ],
  "communities": [
    {
      "id": 0,
      "title": "Apex Capital and Nova AI Investment Dynamics",
      "summary": "The community centered around Apex Capital, Nova AI, and key figures such as Robert Kim represents substantial inter-corporate and leadership networks. Apex Capital's funding within Nova AI's Series B round, combined with its leadership dynamics, outlines a complex, influential interconnection posing both opportunities and strategic impacts within the tech investment sector.",
      "size": 2,
      "color": "#E63946"
    },
    {
      "id": 1,
      "title": "CloudBase and Nova AI Partnership",
      "summary": "The community centers around CloudBase, a prominent cloud computing provider, and its strategic alliance with Nova AI to host the AI platform GraphMind. The collaboration is championed by Hannah Park, CTO of CloudBase, marking a significant moment for enterprise AI solutions. This partnership enhances CloudBase's technical capabilities and positions it as a formidable entity within the cloud computing industry.",
      "size": 2,
      "color": "#2A9D8F"
    },
    {
      "id": 2,
      "title": "DocuMind & AI Document Management Community",
      "summary": "DocuMind, an innovative player in the AI-driven document management sector, spearheaded by former Google engineer Trevor Blake and based in San Francisco, is a competitor to Nova AI. Despite a past scandal, DocuMind has showcased resilience and potential growth, planning an IPO while addressing vulnerabilities identified by David Wu from UC Berkeley.",
      "size": 4,
      "color": "#E9C46A"
    },
    {
      "id": 3,
      "title": "TechGiant Corp and Nova AI Community",
      "summary": "The community revolves around TechGiant Corp, a prominent cloud computing company headquartered in Redmond, and its strategic relationship with Nova AI. This includes TechGiant's investment in Nova AI's Series B funding round and the launch of its competing product, DocuAI. The interaction between these entities highlights TechGiant's strategic push into the AI sector, demonstrating its commitment to innovation and market competitiveness.",
      "size": 3,
      "color": "#5E8FC7"
    },
    {
      "id": 4,
      "title": "Stellar Systems and its Innovative Ventures",
      "summary": "Stellar Systems, a prominent AI company based in Seattle, is at the heart of this community. The company, initially recognized for MedReader, its advanced medical document processing technology, is undergoing leadership-driven strategic pivots, fostering product and market innovation while retaining ties with key figures like founder Leila Nouri. Competitive pressures from Nova AI have prompted Stellar Systems to explore knowledge graph solutions under new CEO James Okonkwo, supported by notable personnel such as Dr. Amy Liu. These developments signify Stellar System's commitment to maintaining its influence in the AI-driven healthcare sector.",
      "size": 6,
      "color": "#F4A261"
    },
    {
      "id": 5,
      "title": "Nova AI and Partners",
      "summary": "The Nova AI community is a dynamic network centered around the innovative AI company, Nova AI, and includes influential individuals and entities such as Priya Kapoor, Horizon Ventures, and TechStar Japan. The community is characterized by significant technological contributions, strategic partnerships, and market expansion efforts. The relationships among these entities drive Nova AI's success and ongoing influence in the AI sector.",
      "size": 13,
      "color": "#A8DADC"
    },
    {
      "id": 6,
      "title": "Nova AI and TechStar Japan Collaborations",
      "summary": "The community under analysis revolves around pivotal collaborations between Nova AI, TechStar Japan, and Y Combinator. Key figures such as Sofia Reyes and Yuki Tanaka are instrumental in the community's functioning, focusing on innovative technological solutions for language-specific applications. These collaborations represent a structured framework of strategic partnerships and technological advancements, reflecting a commitment to innovation and integration within the digital landscape.",
      "size": 3,
      "color": "#BB8FCE"
    }
  ],
  "stats": {
    "entities": 76,
    "relationships": 63,
    "communities": 7
  }
};
